{% set name = "lb-nightly-rpc" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-rpc-{{ version }}.tar.gz
  sha256: 07d8c40cbc7dde58aeeca1693632e098d3175c86fcb3b410a69bf9ceba6dea91

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - celery >=5.1.2,<6.0.0
    - lb-nightly-configuration >=0.1.4,<0.2.0
    - lbplatformutils >=4.3.6,<5.0.0
    - mysqlclient >=2.0.3,<3.0.0
    - python >=3.8,<4.0

test:
  imports:
    - lb
    - lb.nightly.rpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lb-nightly-rpc/
  summary: Celery inter-process interface for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maszyman
